Linux Support
TelicSolutionsInc/AngularBoilerplate pull request #8
Opened 2022-04-02 09:29 UTC by Mubashir-Ansari

2022-04-02 15:04 UTC, Mubashir-Ansari commented
@wajeehmisbahkhan Request for review.

2022-04-02 18:56 UTC, wajeehmisbahkhan requested changes

2022-04-02 18:56 UTC, wajeehmisbahkhan commented on Docs/Snapcraft.md
> +# Linux Electron App build, Snapcraft Release, and Actions
Rename file to LINUX.md

2022-04-02 18:56 UTC, wajeehmisbahkhan commented on Docs/Snapcraft.md
> +This action is already written in [.github/workflows/sanpcraft.yaml](https://github.com/Efshal/boilerplate-monorepo/blob/main/.github/workflows/snapcraft-publish.yml), you have to first produce data
Update to correct links

2022-04-02 18:56 UTC, wajeehmisbahkhan commented on main.js
> +// "use strict";
Remove dead code and update file to TypeScript instead of JS

2022-04-03 18:03 UTC, wajeehmisbahkhan requested changes

2022-04-03 18:03 UTC, wajeehmisbahkhan commented on .github/workflows/snapcraft-publish.yml
> +name: Snapcraft Publish Action
Rename this file to `deploy-linux` and create another action which only builds the linux package but does not upload it. This should run on pull request.

2022-04-03 18:03 UTC, wajeehmisbahkhan commented on Docs/LINUX.md
> +This action is already written in [.github/workflows/sanpcraft.yaml](https://github.com/Efshal/boilerplate-monorepo/blob/main/.github/workflows/snapcraft-publish.yml), you have to first produce data
update URL

2022-04-03 19:58 UTC, Mubashir-Ansari commented
@wajeehmisbahkhan changes done.

2022-04-04 00:58 UTC, wajeehmisbahkhan approved these changes

2022-04-04 00:58 UTC, merged